// chinese.js
// Все слова из фото. Порядок наоборот: последнее фото идет первым.
// Все слова относятся к UNIT-1.

const CHINESE_WORDS = [
  // 1) Phone / Address — последнее фото первым
  { hanzi: "电话", pinyin: "diànhuà", meaning: "telephone", example: "我有电话。", russian: "телефон" },
  { hanzi: "号码", pinyin: "hàomǎ", meaning: "number, code", example: "你的号码是多少？", russian: "номер, код" },
  { hanzi: "手机", pinyin: "shǒujī", meaning: "mobile phone", example: "这是我的手机。", russian: "мобильный телефон" },
  { hanzi: "多少", pinyin: "duōshao", meaning: "what, how many/much", example: "多少钱？", russian: "сколько" },
  { hanzi: "公园", pinyin: "gōngyuán", meaning: "park", example: "公园在附近。", russian: "парк" },
  { hanzi: "路", pinyin: "lù", meaning: "road", example: "这条路很长。", russian: "дорога" },
  { hanzi: "号", pinyin: "hào", meaning: "number, date", example: "一号。", russian: "номер, дата" },
  { hanzi: "新", pinyin: "xīn", meaning: "new", example: "这是新手机。", russian: "новый" },
  { hanzi: "地址", pinyin: "dìzhǐ", meaning: "address", example: "你的地址是什么？", russian: "адрес" },
  { hanzi: "大学", pinyin: "dàxué", meaning: "university", example: "我在大学学习。", russian: "университет" },
  { hanzi: "公寓", pinyin: "gōngyù", meaning: "block of flats, apartment building", example: "我住在公寓。", russian: "квартира, жилой дом" },
  { hanzi: "房间", pinyin: "fángjiān", meaning: "room", example: "我的房间很大。", russian: "комната" },
  { hanzi: "可以", pinyin: "kěyǐ", meaning: "may, can", example: "我可以去吗？", russian: "можно, мочь" },
  { hanzi: "给", pinyin: "gěi", meaning: "give, to", example: "我给你电话。", russian: "дать, для, к" },
  { hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "make a phone call", example: "我给妈妈打电话。", russian: "звонить по телефону" },
  { hanzi: "发件人", pinyin: "fājiànrén", meaning: "sender", example: "发件人是谁？", russian: "отправитель" },
  { hanzi: "收到", pinyin: "shōudào", meaning: "receive", example: "我收到短信。", russian: "получать" },
  { hanzi: "谢谢", pinyin: "xièxie", meaning: "thank you", example: "谢谢你！", russian: "спасибо" },
  { hanzi: "收件箱", pinyin: "shōujiànxiāng", meaning: "inbox", example: "收件箱里有邮件。", russian: "входящие сообщения" },
  { hanzi: "发送", pinyin: "fāsòng", meaning: "send", example: "我发送短信。", russian: "отправлять" },
  { hanzi: "短信", pinyin: "duǎnxìn", meaning: "message", example: "我收到短信。", russian: "сообщение, SMS" },
  { hanzi: "退出", pinyin: "tuìchū", meaning: "exit, go back", example: "请退出。", russian: "выйти, вернуться" },
  { hanzi: "省", pinyin: "shěng", meaning: "province", example: "这是一个省。", russian: "провинция" },
  { hanzi: "市", pinyin: "shì", meaning: "city", example: "我住在阿拉木图市。", russian: "город" },
  { hanzi: "区", pinyin: "qū", meaning: "district", example: "这个区很大。", russian: "район" },
  { hanzi: "街", pinyin: "jiē", meaning: "street", example: "这条街很长。", russian: "улица" },

  // 2) Dates / Week / Food
  { hanzi: "二月", pinyin: "Èryuè", meaning: "February", example: "我的生日在二月。", russian: "февраль" },
  { hanzi: "月", pinyin: "yuè", meaning: "month", example: "一月是第一个月。", russian: "месяц" },
  { hanzi: "生日", pinyin: "shēngrì", meaning: "birthday", example: "今天是我的生日。", russian: "день рождения" },
  { hanzi: "真的", pinyin: "zhēn de", meaning: "really", example: "真的吗？", russian: "правда, действительно" },
  { hanzi: "今天", pinyin: "jīntiān", meaning: "today", example: "今天我学习中文。", russian: "сегодня" },
  { hanzi: "几", pinyin: "jǐ", meaning: "how many", example: "今天几号？", russian: "сколько, который" },
  { hanzi: "星期天", pinyin: "Xīngqītiān", meaning: "Sunday spoken", example: "星期天我休息。", russian: "воскресенье" },
  { hanzi: "星期", pinyin: "xīngqī", meaning: "week", example: "这个星期我很忙。", russian: "неделя" },
  { hanzi: "我们", pinyin: "wǒmen", meaning: "we, us", example: "我们去学校。", russian: "мы" },
  { hanzi: "吃饭", pinyin: "chīfàn", meaning: "have a meal", example: "我们一起吃饭。", russian: "кушать, есть" },
  { hanzi: "吃", pinyin: "chī", meaning: "eat", example: "我吃饭。", russian: "есть, кушать" },
  { hanzi: "去", pinyin: "qù", meaning: "go", example: "我去大学。", russian: "идти, ехать" },
  { hanzi: "厨房", pinyin: "chúfáng", meaning: "kitchen", example: "妈妈在厨房。", russian: "кухня" },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "how about", example: "这个怎么样？", russian: "как насчет, как" },
  { hanzi: "那里", pinyin: "nàli", meaning: "there", example: "他在那里。", russian: "там" },
  { hanzi: "中餐", pinyin: "Zhōngcān", meaning: "Chinese food", example: "我喜欢中餐。", russian: "китайская еда" },
  { hanzi: "餐", pinyin: "cān", meaning: "cuisine, meal", example: "这餐很好吃。", russian: "еда, прием пищи" },
  { hanzi: "好吃", pinyin: "hǎochī", meaning: "tasty", example: "这个菜很好吃。", russian: "вкусный" },
  { hanzi: "没问题", pinyin: "méi wèntí", meaning: "no problem", example: "没问题！", russian: "нет проблем" },
  { hanzi: "六月", pinyin: "Liùyuè", meaning: "June", example: "六月天气很好。", russian: "июнь" },
  { hanzi: "日", pinyin: "rì", meaning: "date written", example: "六月一日。", russian: "день, число" },
  { hanzi: "星期日", pinyin: "Xīngqīrì", meaning: "Sunday written", example: "星期日我休息。", russian: "воскресенье" },
  { hanzi: "星期一", pinyin: "Xīngqīyī", meaning: "Monday", example: "星期一我上课。", russian: "понедельник" },
  { hanzi: "星期二", pinyin: "Xīngqī'èr", meaning: "Tuesday", example: "星期二我学习。", russian: "вторник" },
  { hanzi: "星期三", pinyin: "Xīngqīsān", meaning: "Wednesday", example: "星期三我去学校。", russian: "среда" },
  { hanzi: "星期四", pinyin: "Xīngqīsì", meaning: "Thursday", example: "星期四我很忙。", russian: "четверг" },
  { hanzi: "星期五", pinyin: "Xīngqīwǔ", meaning: "Friday", example: "星期五我看电影。", russian: "пятница" },
  { hanzi: "星期六", pinyin: "Xīngqīliù", meaning: "Saturday", example: "星期六我休息。", russian: "суббота" },
  { hanzi: "打", pinyin: "dǎ", meaning: "play ball game with hands", example: "我打篮球。", russian: "играть, бить" },
  { hanzi: "跟", pinyin: "gēn", meaning: "with", example: "我跟朋友去。", russian: "с, вместе с" },
  { hanzi: "见面", pinyin: "jiànmiàn", meaning: "meet up", example: "我们明天见面。", russian: "встречаться" },
  { hanzi: "看", pinyin: "kàn", meaning: "read, see", example: "我看书。", russian: "смотреть, читать" },
  { hanzi: "书", pinyin: "shū", meaning: "book", example: "这是我的书。", russian: "книга" },
  { hanzi: "上班", pinyin: "shàngbān", meaning: "go to work", example: "爸爸去上班。", russian: "идти на работу" },
  { hanzi: "学", pinyin: "xué", meaning: "study, learn", example: "我学中文。", russian: "учиться, изучать" },
  { hanzi: "派对", pinyin: "pàiduì", meaning: "party", example: "我们去派对。", russian: "вечеринка" },
  { hanzi: "一月", pinyin: "Yīyuè", meaning: "January", example: "一月很冷。", russian: "январь" },
  { hanzi: "五月", pinyin: "Wǔyuè", meaning: "May", example: "五月天气很好。", russian: "май" },
  { hanzi: "七月", pinyin: "Qīyuè", meaning: "July", example: "七月很热。", russian: "июль" },
  { hanzi: "九月", pinyin: "Jiǔyuè", meaning: "September", example: "九月开学。", russian: "сентябрь" },
  { hanzi: "去年", pinyin: "qùnián", meaning: "last year", example: "去年我学习中文。", russian: "прошлый год" },
  { hanzi: "今年", pinyin: "jīnnián", meaning: "this year", example: "今年是2026年。", russian: "этот год" },
  { hanzi: "明年", pinyin: "míngnián", meaning: "next year", example: "明年我去中国。", russian: "следующий год" },
  { hanzi: "昨天", pinyin: "zuótiān", meaning: "yesterday", example: "昨天我很忙。", russian: "вчера" },
  { hanzi: "明天", pinyin: "míngtiān", meaning: "tomorrow", example: "明天见！", russian: "завтра" },
  { hanzi: "上个", pinyin: "shàngge", meaning: "last", example: "上个星期。", russian: "прошлый" },
  { hanzi: "这个", pinyin: "zhège", meaning: "this", example: "这个很好。", russian: "этот" },
  { hanzi: "下个", pinyin: "xiàge", meaning: "next", example: "下个星期。", russian: "следующий" },

  // 3) Time / Activities
  { hanzi: "周末", pinyin: "zhōumò", meaning: "weekend", example: "周末我看电影。", russian: "выходные" },
  { hanzi: "有", pinyin: "yǒu", meaning: "have", example: "我有时间。", russian: "иметь, есть" },
  { hanzi: "时间", pinyin: "shíjiān", meaning: "time", example: "你有时间吗？", russian: "время" },
  { hanzi: "要", pinyin: "yào", meaning: "want", example: "我要去电影院。", russian: "хотеть, нужно" },
  { hanzi: "爷爷", pinyin: "yéye", meaning: "grandfather", example: "我爷爷很好。", russian: "дедушка" },
  { hanzi: "计划", pinyin: "jìhuà", meaning: "plan", example: "你有什么计划？", russian: "план" },
  { hanzi: "没有", pinyin: "méiyǒu", meaning: "not have", example: "我没有时间。", russian: "нет, не иметь" },
  { hanzi: "一起", pinyin: "yìqǐ", meaning: "together", example: "我们一起去吧。", russian: "вместе" },
  { hanzi: "电影", pinyin: "diànyǐng", meaning: "movie, film", example: "我想看电影。", russian: "фильм, кино" },
  { hanzi: "几点", pinyin: "jǐ diǎn", meaning: "what time", example: "电影几点开始？", russian: "во сколько" },
  { hanzi: "点", pinyin: "diǎn", meaning: "o'clock", example: "三点。", russian: "час, часов" },
  { hanzi: "半", pinyin: "bàn", meaning: "half", example: "三点半。", russian: "половина" },
  { hanzi: "开始", pinyin: "kāishǐ", meaning: "start", example: "电影开始了。", russian: "начинать" },
  { hanzi: "电影院", pinyin: "diànyǐngyuàn", meaning: "cinema", example: "电影院在哪儿？", russian: "кинотеатр" },
  { hanzi: "门口", pinyin: "ménkǒu", meaning: "entrance, doorway", example: "我在门口等你。", russian: "вход, у двери" },
  { hanzi: "见", pinyin: "jiàn", meaning: "see, meet", example: "明天见！", russian: "видеть, встречать" },
  { hanzi: "太", pinyin: "tài", meaning: "very, too", example: "太好了！", russian: "слишком, очень" },
  { hanzi: "了", pinyin: "le", meaning: "particle", example: "电影开始了。", russian: "частица" },
  { hanzi: "朋友", pinyin: "péngyou", meaning: "friend", example: "他是我的朋友。", russian: "друг" },
  { hanzi: "晚上", pinyin: "wǎnshang", meaning: "evening", example: "晚上我看电影。", russian: "вечер" },
  { hanzi: "事", pinyin: "shì", meaning: "thing, matter", example: "我有事。", russian: "дело" },
  { hanzi: "上午", pinyin: "shàngwǔ", meaning: "morning", example: "上午我学习。", russian: "утро, до обеда" },
  { hanzi: "分", pinyin: "fēn", meaning: "minute", example: "五分。", russian: "минута" },
  { hanzi: "刻", pinyin: "kè", meaning: "quarter of an hour", example: "三点一刻。", russian: "четверть часа" },
  { hanzi: "英语", pinyin: "Yīngyǔ", meaning: "English", example: "我学习英语。", russian: "английский язык" },
  { hanzi: "中午", pinyin: "zhōngwǔ", meaning: "noon", example: "中午我吃饭。", russian: "полдень" },
  { hanzi: "菜", pinyin: "cài", meaning: "food, dish", example: "这个菜很好吃。", russian: "блюдо, еда" },
  { hanzi: "下午", pinyin: "xiàwǔ", meaning: "afternoon", example: "下午我跑步。", russian: "после обеда" },
  { hanzi: "跑步", pinyin: "pǎobù", meaning: "jog", example: "我喜欢跑步。", russian: "бегать" },
  { hanzi: "写", pinyin: "xiě", meaning: "write", example: "我写电子邮件。", russian: "писать" },
  { hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "email", example: "我写电子邮件。", russian: "электронная почта" },
  { hanzi: "唱歌", pinyin: "chànggē", meaning: "sing a song", example: "她喜欢唱歌。", russian: "петь" },
  { hanzi: "奶奶", pinyin: "nǎinai", meaning: "grandmother", example: "我奶奶很好。", russian: "бабушка" },
  { hanzi: "到", pinyin: "dào", meaning: "get to, arrive", example: "我到学校了。", russian: "прибывать, доходить" },
  { hanzi: "运动", pinyin: "yùndòng", meaning: "sports", example: "我喜欢运动。", russian: "спорт" },
  { hanzi: "晚饭", pinyin: "wǎnfàn", meaning: "dinner", example: "晚上我吃晚饭。", russian: "ужин" },
  { hanzi: "音乐", pinyin: "yīnyuè", meaning: "music", example: "我听音乐。", russian: "музыка" },
  { hanzi: "听", pinyin: "tīng", meaning: "listen", example: "我听音乐。", russian: "слушать" },
  { hanzi: "音乐会", pinyin: "yīnyuèhuì", meaning: "concert", example: "我们去音乐会。", russian: "концерт" },
  { hanzi: "生日卡", pinyin: "shēngrìkǎ", meaning: "birthday card", example: "我写生日卡。", russian: "открытка на день рождения" },
  { hanzi: "博客", pinyin: "bókè", meaning: "blog", example: "我写博客。", russian: "блог" },
  { hanzi: "游泳", pinyin: "yóuyǒng", meaning: "swim", example: "我喜欢游泳。", russian: "плавать" },
  { hanzi: "买", pinyin: "mǎi", meaning: "buy", example: "我买东西。", russian: "покупать" },
  { hanzi: "东西", pinyin: "dōngxi", meaning: "thing", example: "我买东西。", russian: "вещь, вещи" },
  { hanzi: "电视", pinyin: "diànshì", meaning: "television", example: "我看电视。", russian: "телевизор" },
  { hanzi: "比赛", pinyin: "bǐsài", meaning: "competition, match", example: "我看比赛。", russian: "соревнование, матч" },

  // 4) Shopping / Clothes
  { hanzi: "售货员", pinyin: "shòuhuòyuán", meaning: "shop assistant", example: "售货员很热情。", russian: "продавец" },
  { hanzi: "衣服", pinyin: "yīfu", meaning: "clothes", example: "这件衣服很好看。", russian: "одежда" },
  { hanzi: "条", pinyin: "tiáo", meaning: "measure word", example: "一条裙子。", russian: "счетное слово" },
  { hanzi: "裙子", pinyin: "qúnzi", meaning: "skirt", example: "这条裙子很漂亮。", russian: "юбка" },
  { hanzi: "来", pinyin: "lái", meaning: "come", example: "你来这边。", russian: "приходить" },
  { hanzi: "这边", pinyin: "zhèbian", meaning: "this way", example: "请来这边。", russian: "сюда, в эту сторону" },
  { hanzi: "红", pinyin: "hóng", meaning: "red", example: "我喜欢红色。", russian: "красный" },
  { hanzi: "蓝色", pinyin: "lánsè", meaning: "blue", example: "蓝色衣服很好看。", russian: "синий" },
  { hanzi: "黑色", pinyin: "hēisè", meaning: "black", example: "我买黑色裤子。", russian: "черный" },
  { hanzi: "好看", pinyin: "hǎokàn", meaning: "good-looking", example: "这件衣服很好看。", russian: "красивый" },
  { hanzi: "试", pinyin: "shì", meaning: "try", example: "我可以试吗？", russian: "примерять" },
  { hanzi: "不错", pinyin: "bùcuò", meaning: "not bad", example: "这件衣服不错。", russian: "неплохо" },
  { hanzi: "钱", pinyin: "qián", meaning: "money", example: "我没有钱。", russian: "деньги" },
  { hanzi: "百", pinyin: "bǎi", meaning: "hundred", example: "一百块。", russian: "сто" },
  { hanzi: "块", pinyin: "kuài", meaning: "yuan", example: "这件衣服一百块。", russian: "юань" },
  { hanzi: "便宜", pinyin: "piányi", meaning: "cheap", example: "这个很便宜。", russian: "дешевый" },
  { hanzi: "一点儿", pinyin: "yìdiǎnr", meaning: "a little", example: "便宜一点儿吧。", russian: "немного" },
  { hanzi: "价钱", pinyin: "jiàqian", meaning: "price", example: "价钱贵吗？", russian: "цена" },
  { hanzi: "贵", pinyin: "guì", meaning: "expensive", example: "这条裙子很贵。", russian: "дорогой" },
  { hanzi: "吧", pinyin: "ba", meaning: "particle", example: "我们走吧。", russian: "частица предложения" },
  { hanzi: "书店", pinyin: "shūdiàn", meaning: "bookshop", example: "书店在前边。", russian: "книжный магазин" },
  { hanzi: "服装市场", pinyin: "fúzhuāng shìchǎng", meaning: "clothes market", example: "我们去服装市场。", russian: "рынок одежды" },
  { hanzi: "远", pinyin: "yuǎn", meaning: "far away", example: "商店很远。", russian: "далеко" },
  { hanzi: "裤子", pinyin: "kùzi", meaning: "trousers", example: "我买裤子。", russian: "брюки" },
  { hanzi: "T恤", pinyin: "tīxù", meaning: "T-shirt", example: "这件T恤很好看。", russian: "футболка" },
  { hanzi: "白色", pinyin: "báisè", meaning: "white", example: "我喜欢白色。", russian: "белый" },
  { hanzi: "有名", pinyin: "yǒumíng", meaning: "famous", example: "这个商店很有名。", russian: "известный" },
  { hanzi: "购物中心", pinyin: "gòuwù zhōngxīn", meaning: "shopping centre", example: "购物中心很大。", russian: "торговый центр" },
  { hanzi: "这里", pinyin: "zhèlǐ", meaning: "here", example: "这里有很多衣服。", russian: "здесь" },
  { hanzi: "双", pinyin: "shuāng", meaning: "pair", example: "一双鞋。", russian: "пара" },
  { hanzi: "鞋", pinyin: "xié", meaning: "shoes", example: "我买一双鞋。", russian: "обувь" },
  { hanzi: "件", pinyin: "jiàn", meaning: "item, piece", example: "一件大衣。", russian: "счетное слово для одежды" },
  { hanzi: "大衣", pinyin: "dàyī", meaning: "coat", example: "这件大衣很贵。", russian: "пальто" },
  { hanzi: "每", pinyin: "měi", meaning: "every, each", example: "每件衣服都很好看。", russian: "каждый" },
  { hanzi: "很多", pinyin: "hěn duō", meaning: "a lot of", example: "这里有很多衣服。", russian: "много" },
  { hanzi: "超市", pinyin: "chāoshì", meaning: "supermarket", example: "超市在附近。", russian: "супермаркет" },
  { hanzi: "绿色", pinyin: "lǜsè", meaning: "green", example: "绿色毛衣很好看。", russian: "зеленый" },
  { hanzi: "黄色", pinyin: "huángsè", meaning: "yellow", example: "黄色围巾很漂亮。", russian: "желтый" },
  { hanzi: "毛衣", pinyin: "máoyī", meaning: "sweater", example: "我买毛衣。", russian: "свитер" },
  { hanzi: "围巾", pinyin: "wéijīn", meaning: "scarf", example: "这条围巾很便宜。", russian: "шарф" },
  { hanzi: "短裤", pinyin: "duǎnkù", meaning: "shorts", example: "夏天我穿短裤。", russian: "шорты" },
  { hanzi: "牛仔裤", pinyin: "niúzǎikù", meaning: "jeans", example: "我喜欢牛仔裤。", russian: "джинсы" },
  { hanzi: "衬衫", pinyin: "chènshān", meaning: "shirt", example: "这件衬衫不错。", russian: "рубашка" },
  { hanzi: "帽子", pinyin: "màozi", meaning: "hat", example: "帽子很好看。", russian: "шапка, кепка" },
  { hanzi: "连衣裙", pinyin: "liányīqún", meaning: "one-piece dress", example: "这条连衣裙很漂亮。", russian: "платье" },

  // 5) Directions / Places — первое фото стало последним
  { hanzi: "哪儿", pinyin: "nǎr", meaning: "where", example: "银行在哪儿？", russian: "где" },
  { hanzi: "楼", pinyin: "lóu", meaning: "building, storey", example: "银行在三楼。", russian: "здание, этаж" },
  { hanzi: "怎么", pinyin: "zěnme", meaning: "how", example: "去银行怎么走？", russian: "как" },
  { hanzi: "走", pinyin: "zǒu", meaning: "walk, go", example: "我们走吧。", russian: "идти, ходить" },
  { hanzi: "路人", pinyin: "lùrén", meaning: "passerby", example: "路人帮我找银行。", russian: "прохожий" },
  { hanzi: "邮局", pinyin: "yóujú", meaning: "post office", example: "邮局在银行旁边。", russian: "почта" },
  { hanzi: "后边", pinyin: "hòubian", meaning: "back, behind", example: "学校在邮局后边。", russian: "сзади, позади" },
  { hanzi: "往", pinyin: "wǎng", meaning: "towards", example: "往前走。", russian: "в сторону, к" },
  { hanzi: "南边", pinyin: "nánbian", meaning: "south", example: "公园在南边。", russian: "юг, южная сторона" },
  { hanzi: "离", pinyin: "lí", meaning: "away from", example: "学校离银行很近。", russian: "от, на расстоянии от" },
  { hanzi: "这儿", pinyin: "zhèr", meaning: "here", example: "我在这儿。", russian: "здесь" },
  { hanzi: "对", pinyin: "duì", meaning: "right, correct", example: "你说得对。", russian: "правильно, верно" },
  { hanzi: "银行", pinyin: "yínháng", meaning: "bank", example: "银行在哪儿？", russian: "банк" },
  { hanzi: "附近", pinyin: "fùjìn", meaning: "vicinity, nearby", example: "附近有邮局吗？", russian: "рядом, поблизости" },
  { hanzi: "前边", pinyin: "qiánbian", meaning: "front", example: "银行在前边。", russian: "спереди, впереди" },
  { hanzi: "分钟", pinyin: "fēnzhōng", meaning: "minute", example: "走五分钟就到了。", russian: "минута" },
  { hanzi: "左右", pinyin: "zuǒyòu", meaning: "about", example: "十分钟左右。", russian: "примерно, около" },
  { hanzi: "东边", pinyin: "dōngbian", meaning: "east side", example: "银行在东边。", russian: "восточная сторона" },
  { hanzi: "西边", pinyin: "xībian", meaning: "west side", example: "邮局在西边。", russian: "западная сторона" },
  { hanzi: "北边", pinyin: "běibian", meaning: "north side", example: "学校在北边。", russian: "северная сторона" }
].map((item) => ({
  unit: "UNIT-1",
  ...item
}));