// chinese.js
// Все слова относятся к UNIT-1.
// Карточка показывает: иероглиф, перевод, pinyin, meaning, example, lexical explanation.

const CHINESE_PARTS = {
  "电": "электричество",
  "话": "речь, слова",
  "号": "номер, знак",
  "码": "код, цифровое обозначение",
  "手": "рука",
  "机": "машина, устройство",
  "多": "много",
  "少": "мало",
  "公": "общественный",
  "园": "сад, парк",
  "路": "дорога",
  "新": "новый",
  "地": "место, земля",
  "址": "местонахождение, адрес",
  "大": "большой",
  "学": "учёба, учиться",
  "寓": "жильё",
  "房": "дом, помещение",
  "间": "пространство, комната",
  "可": "можно",
  "以": "можно, с помощью",
  "给": "дать, передать",
  "打": "бить, делать действие рукой",
  "发": "отправлять",
  "件": "предмет, документ, вещь",
  "人": "человек",
  "收": "получать",
  "到": "дойти, прибыть",
  "谢": "благодарить",
  "箱": "ящик, коробка",
  "送": "посылать, доставлять",
  "短": "короткий",
  "信": "письмо, сообщение",
  "退": "отступать, выходить",
  "出": "выходить",
  "省": "провинция",
  "市": "город, рынок",
  "区": "район",
  "街": "улица",

  "二": "два",
  "月": "месяц, луна",
  "生": "рождаться, жизнь",
  "日": "день, солнце",
  "真": "настоящий, правда",
  "今": "нынешний",
  "天": "день, небо",
  "几": "сколько",
  "星": "звезда",
  "期": "период, срок",
  "我": "я",
  "们": "суффикс множественного числа",
  "吃": "есть, кушать",
  "饭": "еда, рис",
  "去": "идти, уходить",
  "厨": "кухня",
  "怎": "как",
  "么": "служебная часть вопросительных слов",
  "样": "вид, образ",
  "那": "тот, там",
  "里": "внутри, место",
  "中": "Китай, середина",
  "餐": "еда, приём пищи",
  "好": "хороший",
  "没": "нет, не иметь",
  "问": "спрашивать",
  "题": "тема, вопрос",
  "六": "шесть",
  "一": "один",
  "三": "три",
  "四": "четыре",
  "五": "пять",
  "跟": "с, вместе с",
  "见": "видеть, встречать",
  "面": "лицо, поверхность",
  "看": "смотреть, читать",
  "书": "книга",
  "上": "верх, идти на",
  "班": "смена, работа",
  "派": "группа, направление",
  "对": "пара, напротив, правильно",
  "七": "семь",
  "九": "девять",
  "年": "год",
  "昨": "вчерашний",
  "明": "светлый, следующий",
  "个": "счётное слово",
  "下": "низ, следующий",

  "周": "неделя, круг",
  "末": "конец",
  "有": "иметь, есть",
  "时": "время",
  "要": "хотеть, нужно",
  "爷": "дедушка",
  "计": "считать, планировать",
  "划": "планировать, чертить",
  "起": "подниматься, вместе",
  "影": "тень, изображение",
  "点": "точка, час",
  "半": "половина",
  "开": "открывать, начинать",
  "始": "начало",
  "院": "учреждение, двор",
  "门": "дверь",
  "口": "рот, вход",
  "太": "слишком, очень",
  "了": "служебная частица завершения действия",
  "朋": "друг",
  "友": "друг",
  "晚": "вечер, поздно",
  "事": "дело",
  "午": "полдень",
  "分": "минута, часть",
  "刻": "четверть часа, момент",
  "英": "английский, герой",
  "语": "язык, речь",
  "菜": "блюдо, овощ",
  "跑": "бежать",
  "步": "шаг",
  "写": "писать",
  "子": "суффикс существительного",
  "邮": "почта",
  "奶": "бабушка, молоко",
  "运": "двигаться, перевозить",
  "动": "двигаться",
  "音": "звук",
  "乐": "музыка, радость",
  "会": "собрание, уметь",
  "卡": "карточка",
  "博": "широкий, блог",
  "客": "гость",
  "游": "плавать, путешествовать",
  "泳": "плавание",
  "买": "покупать",
  "东": "восток",
  "西": "запад",
  "视": "смотреть",
  "比": "сравнивать",
  "赛": "соревнование",

  "售": "продавать",
  "货": "товар",
  "员": "работник, сотрудник",
  "衣": "одежда",
  "服": "одежда, служить",
  "条": "длинный предмет, счётное слово",
  "裙": "юбка",
  "来": "приходить",
  "这": "этот",
  "边": "сторона",
  "红": "красный",
  "蓝": "синий",
  "色": "цвет",
  "黑": "чёрный",
  "试": "пробовать, примерять",
  "错": "ошибка, плохой",
  "钱": "деньги",
  "百": "сто",
  "块": "кусок, юань",
  "便": "удобный, дешёвый",
  "宜": "подходящий",
  "价": "цена",
  "贵": "дорогой",
  "吧": "частица предложения",
  "店": "магазин",
  "装": "одежда, наряд",
  "场": "площадка, рынок",
  "远": "далеко",
  "裤": "брюки",
  "白": "белый",
  "名": "имя, известность",
  "购": "покупать",
  "物": "вещь",
  "心": "центр, сердце",
  "双": "пара",
  "鞋": "обувь",
  "每": "каждый",
  "很": "очень",
  "超": "супер, сверх",
  "绿": "зелёный",
  "黄": "жёлтый",
  "毛": "шерсть",
  "围": "оборачивать",
  "巾": "платок, ткань",
  "牛": "корова",
  "仔": "молодой, деталь слова",
  "衬": "подкладка, рубашка",
  "衫": "рубашка",
  "帽": "шапка",
  "连": "соединять",

  "哪": "какой, где",
  "儿": "суффикс разговорной речи",
  "楼": "здание, этаж",
  "走": "идти",
  "后": "задний, после",
  "往": "в сторону",
  "南": "юг",
  "离": "от, расстояние",
  "银": "серебро",
  "行": "банк, ряд, идти",
  "近": "близко",
  "前": "передний",
  "钟": "час, колокол",
  "左": "лево",
  "右": "право",
  "北": "север"
};

function makeChineseExplanation(item) {
  const hanzi = String(item.hanzi || "");
  const chars = [...hanzi].filter((char) => CHINESE_PARTS[char]);

  if (!chars.length) {
    return `${hanzi} — китайское слово. Значение: ${item.russian || item.meaning || ""}.`;
  }

  const parts = chars
    .map((char) => `${char} — ${CHINESE_PARTS[char]}`)
    .join(", ");

  return `${parts}. Вместе ${hanzi} значит: ${item.russian || item.meaning || ""}.`;
}

const CHINESE_WORDS = [
  { hanzi: "电话", pinyin: "diànhuà", meaning: "telephone", example: "我有电话。", russian: "телефон" },
  { hanzi: "号码", pinyin: "hàomǎ", meaning: "number, code", example: "你的号码是多少？", russian: "номер, код" },
  { hanzi: "手机", pinyin: "shǒujī", meaning: "mobile phone", example: "这是我的手机。", russian: "мобильный телефон" },
  { hanzi: "多少", pinyin: "duōshao", meaning: "what, how many/much", example: "多少钱？", russian: "сколько" },
  { hanzi: "公园", pinyin: "gōngyuán", meaning: "park", example: "公园在附近。", russian: "парк" },
  { hanzi: "路", pinyin: "lù", meaning: "road", example: "这条路很长。", russian: "дорога" },
  { hanzi: "号", pinyin: "hào", meaning: "number, date", example: "一号。", russian: "номер, дата" },
  { hanzi: "新", pinyin: "xīn", meaning: "new", example: "这是新手机。", russian: "новый" },
  { hanzi: "地址", pinyin: "dìzhǐ", meaning: "address", example: "你的地址是什么？", russian: "адрес" },
  { hanzi: "大学", pinyin: "dàxué", meaning: "university", example: "我在大学学习。", russian: "университет" },
  { hanzi: "公寓", pinyin: "gōngyù", meaning: "block of flats, apartment building", example: "我住在公寓。", russian: "квартира, жилой дом" },
  { hanzi: "房间", pinyin: "fángjiān", meaning: "room", example: "我的房间很大。", russian: "комната" },
  { hanzi: "可以", pinyin: "kěyǐ", meaning: "may, can", example: "我可以去吗？", russian: "можно, мочь" },
  { hanzi: "给", pinyin: "gěi", meaning: "give, to", example: "我给你电话。", russian: "дать, для, к" },
  { hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "make a phone call", example: "我给妈妈打电话。", russian: "звонить по телефону" },
  { hanzi: "发件人", pinyin: "fājiànrén", meaning: "sender", example: "发件人是谁？", russian: "отправитель" },
  { hanzi: "收到", pinyin: "shōudào", meaning: "receive", example: "我收到短信。", russian: "получать" },
  { hanzi: "谢谢", pinyin: "xièxie", meaning: "thank you", example: "谢谢你！", russian: "спасибо" },
  { hanzi: "收件箱", pinyin: "shōujiànxiāng", meaning: "inbox", example: "收件箱里有邮件。", russian: "входящие сообщения" },
  { hanzi: "发送", pinyin: "fāsòng", meaning: "send", example: "我发送短信。", russian: "отправлять" },
  { hanzi: "短信", pinyin: "duǎnxìn", meaning: "message", example: "我收到短信。", russian: "сообщение, SMS" },
  { hanzi: "退出", pinyin: "tuìchū", meaning: "exit, go back", example: "请退出。", russian: "выйти, вернуться" },
  { hanzi: "省", pinyin: "shěng", meaning: "province", example: "这是一个省。", russian: "провинция" },
  { hanzi: "市", pinyin: "shì", meaning: "city", example: "我住在阿拉木图市。", russian: "город" },
  { hanzi: "区", pinyin: "qū", meaning: "district", example: "这个区很大。", russian: "район" },
  { hanzi: "街", pinyin: "jiē", meaning: "street", example: "这条街很长。", russian: "улица" },

  { hanzi: "二月", pinyin: "èryuè", meaning: "February", example: "我的生日在二月。", russian: "февраль" },
  { hanzi: "月", pinyin: "yuè", meaning: "month", example: "一月是第一个月。", russian: "месяц" },
  { hanzi: "生日", pinyin: "shēngrì", meaning: "birthday", example: "今天是我的生日。", russian: "день рождения" },
  { hanzi: "真的", pinyin: "zhēn de", meaning: "really", example: "真的吗？", russian: "правда, действительно" },
  { hanzi: "今天", pinyin: "jīntiān", meaning: "today", example: "今天我学习中文。", russian: "сегодня" },
  { hanzi: "几", pinyin: "jǐ", meaning: "how many", example: "今天几号？", russian: "сколько, который" },
  { hanzi: "星期天", pinyin: "xīngqītiān", meaning: "Sunday spoken", example: "星期天我休息。", russian: "воскресенье" },
  { hanzi: "星期", pinyin: "xīngqī", meaning: "week", example: "这个星期我很忙。", russian: "неделя" },
  { hanzi: "我们", pinyin: "wǒmen", meaning: "we, us", example: "我们去学校。", russian: "мы" },
  { hanzi: "吃饭", pinyin: "chīfàn", meaning: "have a meal", example: "我们一起吃饭。", russian: "кушать, есть" },
  { hanzi: "吃", pinyin: "chī", meaning: "eat", example: "我吃饭。", russian: "есть, кушать" },
  { hanzi: "去", pinyin: "qù", meaning: "go", example: "我去大学。", russian: "идти, ехать" },
  { hanzi: "厨房", pinyin: "chúfáng", meaning: "kitchen", example: "妈妈在厨房。", russian: "кухня" },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "how about", example: "这个怎么样？", russian: "как насчет, как" },
  { hanzi: "那里", pinyin: "nàli", meaning: "there", example: "他在那里。", russian: "там" },
  { hanzi: "中餐", pinyin: "zhōngcān", meaning: "Chinese food", example: "我喜欢中餐。", russian: "китайская еда" },
  { hanzi: "餐", pinyin: "cān", meaning: "cuisine, meal", example: "这餐很好吃。", russian: "еда, прием пищи" },
  { hanzi: "好吃", pinyin: "hǎochī", meaning: "tasty", example: "这个菜很好吃。", russian: "вкусный" },
  { hanzi: "没问题", pinyin: "méi wèntí", meaning: "no problem", example: "没问题！", russian: "нет проблем" },
  { hanzi: "六月", pinyin: "liùyuè", meaning: "June", example: "六月天气很好。", russian: "июнь" },
  { hanzi: "日", pinyin: "rì", meaning: "date written", example: "六月一日。", russian: "день, число" },
  { hanzi: "星期日", pinyin: "xīngqīrì", meaning: "Sunday written", example: "星期日我休息。", russian: "воскресенье" },
  { hanzi: "星期一", pinyin: "xīngqīyī", meaning: "Monday", example: "星期一我上课。", russian: "понедельник" },
  { hanzi: "星期二", pinyin: "xīngqī'èr", meaning: "Tuesday", example: "星期二我学习。", russian: "вторник" },
  { hanzi: "星期三", pinyin: "xīngqīsān", meaning: "Wednesday", example: "星期三我去学校。", russian: "среда" },
  { hanzi: "星期四", pinyin: "xīngqīsì", meaning: "Thursday", example: "星期四我很忙。", russian: "четверг" },
  { hanzi: "星期五", pinyin: "xīngqīwǔ", meaning: "Friday", example: "星期五我看电影。", russian: "пятница" },
  { hanzi: "星期六", pinyin: "xīngqīliù", meaning: "Saturday", example: "星期六我休息。", russian: "суббота" },
  { hanzi: "打", pinyin: "dǎ", meaning: "play ball game with hands", example: "我打篮球。", russian: "играть, бить" },
  { hanzi: "跟", pinyin: "gēn", meaning: "with", example: "我跟朋友去。", russian: "с, вместе с" },
  { hanzi: "见面", pinyin: "jiànmiàn", meaning: "meet up", example: "我们明天见面。", russian: "встречаться" },
  { hanzi: "看", pinyin: "kàn", meaning: "read, see", example: "我看书。", russian: "смотреть, читать" },
  { hanzi: "书", pinyin: "shū", meaning: "book", example: "这是我的书。", russian: "книга" },
  { hanzi: "上班", pinyin: "shàngbān", meaning: "go to work", example: "爸爸去上班。", russian: "идти на работу" },
  { hanzi: "学", pinyin: "xué", meaning: "study, learn", example: "我学中文。", russian: "учиться, изучать" },
  { hanzi: "派对", pinyin: "pàiduì", meaning: "party", example: "我们去派对。", russian: "вечеринка" },
  { hanzi: "一月", pinyin: "yīyuè", meaning: "January", example: "一月很冷。", russian: "январь" },
  { hanzi: "五月", pinyin: "wǔyuè", meaning: "May", example: "五月天气很好。", russian: "май" },
  { hanzi: "七月", pinyin: "qīyuè", meaning: "July", example: "七月很热。", russian: "июль" },
  { hanzi: "九月", pinyin: "jiǔyuè", meaning: "September", example: "九月开学。", russian: "сентябрь" },
  { hanzi: "去年", pinyin: "qùnián", meaning: "last year", example: "去年我学习中文。", russian: "прошлый год" },
  { hanzi: "今年", pinyin: "jīnnián", meaning: "this year", example: "今年是2026年。", russian: "этот год" },
  { hanzi: "明年", pinyin: "míngnián", meaning: "next year", example: "明年我去中国。", russian: "следующий год" },
  { hanzi: "昨天", pinyin: "zuótiān", meaning: "yesterday", example: "昨天我很忙。", russian: "вчера" },
  { hanzi: "明天", pinyin: "míngtiān", meaning: "tomorrow", example: "明天见！", russian: "завтра" },
  { hanzi: "上个", pinyin: "shàngge", meaning: "last", example: "上个星期。", russian: "прошлый" },
  { hanzi: "这个", pinyin: "zhège", meaning: "this", example: "这个很好。", russian: "этот" },
  { hanzi: "下个", pinyin: "xiàge", meaning: "next", example: "下个星期。", russian: "следующий" },

  { hanzi: "周末", pinyin: "zhōumò", meaning: "weekend", example: "周末我看电影。", russian: "выходные" },
  { hanzi: "有", pinyin: "yǒu", meaning: "have", example: "我有时间。", russian: "иметь, есть" },
  { hanzi: "时间", pinyin: "shíjiān", meaning: "time", example: "你有时间吗？", russian: "время" },
  { hanzi: "要", pinyin: "yào", meaning: "want", example: "我要去电影院。", russian: "хотеть, нужно" },
  { hanzi: "爷爷", pinyin: "yéye", meaning: "grandfather", example: "我爷爷很好。", russian: "дедушка" },
  { hanzi: "计划", pinyin: "jìhuà", meaning: "plan", example: "你有什么计划？", russian: "план" },
  { hanzi: "没有", pinyin: "méiyǒu", meaning: "not have", example: "我没有时间。", russian: "нет, не иметь" },
  { hanzi: "一起", pinyin: "yìqǐ", meaning: "together", example: "我们一起去吧。", russian: "вместе" },
  { hanzi: "电影", pinyin: "diànyǐng", meaning: "movie, film", example: "我想看电影。", russian: "фильм, кино" },
  { hanzi: "几点", pinyin: "jǐ diǎn", meaning: "what time", example: "电影几点开始？", russian: "во сколько" },
  { hanzi: "点", pinyin: "diǎn", meaning: "o'clock", example: "三点。", russian: "час, часов" },
  { hanzi: "半", pinyin: "bàn", meaning: "half", example: "三点半。", russian: "половина" },
  { hanzi: "开始", pinyin: "kāishǐ", meaning: "start", example: "电影开始了。", russian: "начинать" },
  { hanzi: "电影院", pinyin: "diànyǐngyuàn", meaning: "cinema", example: "电影院在哪儿？", russian: "кинотеатр" },
  { hanzi: "门口", pinyin: "ménkǒu", meaning: "entrance, doorway", example: "我在门口等你。", russian: "вход, у двери" },
  { hanzi: "见", pinyin: "jiàn", meaning: "see, meet", example: "明天见！", russian: "видеть, встречать" },
  { hanzi: "太", pinyin: "tài", meaning: "very, too", example: "太好了！", russian: "слишком, очень" },
  { hanzi: "了", pinyin: "le", meaning: "particle", example: "电影开始了。", russian: "частица" },
  { hanzi: "朋友", pinyin: "péngyou", meaning: "friend", example: "他是我的朋友。", russian: "друг" },
  { hanzi: "晚上", pinyin: "wǎnshang", meaning: "evening", example: "晚上我看电影。", russian: "вечер" },
  { hanzi: "事", pinyin: "shì", meaning: "thing, matter", example: "我有事。", russian: "дело" },
  { hanzi: "上午", pinyin: "shàngwǔ", meaning: "morning", example: "上午我学习。", russian: "утро, до обеда" },
  { hanzi: "分", pinyin: "fēn", meaning: "minute", example: "五分。", russian: "минута" },
  { hanzi: "刻", pinyin: "kè", meaning: "quarter of an hour", example: "三点一刻。", russian: "четверть часа" },
  { hanzi: "英语", pinyin: "yīngyǔ", meaning: "English", example: "我学习英语。", russian: "английский язык" },
  { hanzi: "中午", pinyin: "zhōngwǔ", meaning: "noon", example: "中午我吃饭。", russian: "полдень" },
  { hanzi: "菜", pinyin: "cài", meaning: "food, dish", example: "这个菜很好吃。", russian: "блюдо, еда" },
  { hanzi: "下午", pinyin: "xiàwǔ", meaning: "afternoon", example: "下午我跑步。", russian: "после обеда" },
  { hanzi: "跑步", pinyin: "pǎobù", meaning: "jog", example: "我喜欢跑步。", russian: "бегать" },
  { hanzi: "写", pinyin: "xiě", meaning: "write", example: "我写电子邮件。", russian: "писать" },
  { hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "email", example: "我写电子邮件。", russian: "электронная почта" },
  { hanzi: "唱歌", pinyin: "chànggē", meaning: "sing a song", example: "她喜欢唱歌。", russian: "петь" },
  { hanzi: "奶奶", pinyin: "nǎinai", meaning: "grandmother", example: "我奶奶很好。", russian: "бабушка" },
  { hanzi: "到", pinyin: "dào", meaning: "get to, arrive", example: "我到学校了。", russian: "прибывать, доходить" },
  { hanzi: "运动", pinyin: "yùndòng", meaning: "sports", example: "我喜欢运动。", russian: "спорт" },
  { hanzi: "晚饭", pinyin: "wǎnfàn", meaning: "dinner", example: "晚上我吃晚饭。", russian: "ужин" },
  { hanzi: "音乐", pinyin: "yīnyuè", meaning: "music", example: "我听音乐。", russian: "музыка" },
  { hanzi: "听", pinyin: "tīng", meaning: "listen", example: "我听音乐。", russian: "слушать" },
  { hanzi: "音乐会", pinyin: "yīnyuèhuì", meaning: "concert", example: "我们去音乐会。", russian: "концерт" },
  { hanzi: "生日卡", pinyin: "shēngrìkǎ", meaning: "birthday card", example: "我写生日卡。", russian: "открытка на день рождения" },
  { hanzi: "博客", pinyin: "bókè", meaning: "blog", example: "我写博客。", russian: "блог" },
  { hanzi: "游泳", pinyin: "yóuyǒng", meaning: "swim", example: "我喜欢游泳。", russian: "плавать" },
  { hanzi: "买", pinyin: "mǎi", meaning: "buy", example: "我买东西。", russian: "покупать" },
  { hanzi: "东西", pinyin: "dōngxi", meaning: "thing", example: "我买东西。", russian: "вещь, вещи" },
  { hanzi: "电视", pinyin: "diànshì", meaning: "television", example: "我看电视。", russian: "телевизор" },
  { hanzi: "比赛", pinyin: "bǐsài", meaning: "competition, match", example: "我看比赛。", russian: "соревнование, матч" },

  { hanzi: "售货员", pinyin: "shòuhuòyuán", meaning: "shop assistant", example: "售货员很热情。", russian: "продавец" },
  { hanzi: "衣服", pinyin: "yīfu", meaning: "clothes", example: "这件衣服很好看。", russian: "одежда" },
  { hanzi: "条", pinyin: "tiáo", meaning: "measure word", example: "一条裙子。", russian: "счетное слово" },
  { hanzi: "裙子", pinyin: "qúnzi", meaning: "skirt", example: "这条裙子很漂亮。", russian: "юбка" },
  { hanzi: "来", pinyin: "lái", meaning: "come", example: "你来这边。", russian: "приходить" },
  { hanzi: "这边", pinyin: "zhèbian", meaning: "this way", example: "请来这边。", russian: "сюда, в эту сторону" },
  { hanzi: "红", pinyin: "hóng", meaning: "red", example: "我喜欢红色。", russian: "красный" },
  { hanzi: "蓝色", pinyin: "lánsè", meaning: "blue", example: "蓝色衣服很好看。", russian: "синий" },
  { hanzi: "黑色", pinyin: "hēisè", meaning: "black", example: "我买黑色裤子。", russian: "черный" },
  { hanzi: "好看", pinyin: "hǎokàn", meaning: "good-looking", example: "这件衣服很好看。", russian: "красивый" },
  { hanzi: "试", pinyin: "shì", meaning: "try", example: "我可以试吗？", russian: "примерять" },
  { hanzi: "不错", pinyin: "bùcuò", meaning: "not bad", example: "这件衣服不错。", russian: "неплохо" },
  { hanzi: "钱", pinyin: "qián", meaning: "money", example: "我没有钱。", russian: "деньги" },
  { hanzi: "百", pinyin: "bǎi", meaning: "hundred", example: "一百块。", russian: "сто" },
  { hanzi: "块", pinyin: "kuài", meaning: "yuan", example: "这件衣服一百块。", russian: "юань" },
  { hanzi: "便宜", pinyin: "piányi", meaning: "cheap", example: "这个很便宜。", russian: "дешевый" },
  { hanzi: "一点儿", pinyin: "yìdiǎnr", meaning: "a little", example: "便宜一点儿吧。", russian: "немного" },
  { hanzi: "价钱", pinyin: "jiàqian", meaning: "price", example: "价钱贵吗？", russian: "цена" },
  { hanzi: "贵", pinyin: "guì", meaning: "expensive", example: "这条裙子很贵。", russian: "дорогой" },
  { hanzi: "吧", pinyin: "ba", meaning: "particle", example: "我们走吧。", russian: "частица предложения" },
  { hanzi: "书店", pinyin: "shūdiàn", meaning: "bookshop", example: "书店在前边。", russian: "книжный магазин" },
  { hanzi: "服装市场", pinyin: "fúzhuāng shìchǎng", meaning: "clothes market", example: "我们去服装市场。", russian: "рынок одежды" },
  { hanzi: "远", pinyin: "yuǎn", meaning: "far away", example: "商店很远。", russian: "далеко" },
  { hanzi: "裤子", pinyin: "kùzi", meaning: "trousers", example: "我买裤子。", russian: "брюки" },
  { hanzi: "T恤", pinyin: "tīxù", meaning: "T-shirt", example: "这件T恤很好看。", russian: "футболка" },
  { hanzi: "白色", pinyin: "báisè", meaning: "white", example: "我喜欢白色。", russian: "белый" },
  { hanzi: "有名", pinyin: "yǒumíng", meaning: "famous", example: "这个商店很有名。", russian: "известный" },
  { hanzi: "购物中心", pinyin: "gòuwù zhōngxīn", meaning: "shopping centre", example: "购物中心很大。", russian: "торговый центр" },
  { hanzi: "这里", pinyin: "zhèlǐ", meaning: "here", example: "这里有很多衣服。", russian: "здесь" },
  { hanzi: "双", pinyin: "shuāng", meaning: "pair", example: "一双鞋。", russian: "пара" },
  { hanzi: "鞋", pinyin: "xié", meaning: "shoes", example: "我买一双鞋。", russian: "обувь" },
  { hanzi: "件", pinyin: "jiàn", meaning: "item, piece", example: "一件大衣。", russian: "счетное слово для одежды" },
  { hanzi: "大衣", pinyin: "dàyī", meaning: "coat", example: "这件大衣很贵。", russian: "пальто" },
  { hanzi: "每", pinyin: "měi", meaning: "every, each", example: "每件衣服都很好看。", russian: "каждый" },
  { hanzi: "很多", pinyin: "hěn duō", meaning: "a lot of", example: "这里有很多衣服。", russian: "много" },
  { hanzi: "超市", pinyin: "chāoshì", meaning: "supermarket", example: "超市在附近。", russian: "супермаркет" },
  { hanzi: "绿色", pinyin: "lǜsè", meaning: "green", example: "绿色毛衣很好看。", russian: "зеленый" },
  { hanzi: "黄色", pinyin: "huángsè", meaning: "yellow", example: "黄色围巾很漂亮。", russian: "желтый" },
  { hanzi: "毛衣", pinyin: "máoyī", meaning: "sweater", example: "我买毛衣。", russian: "свитер" },
  { hanzi: "围巾", pinyin: "wéijīn", meaning: "scarf", example: "这条围巾很便宜。", russian: "шарф" },
  { hanzi: "短裤", pinyin: "duǎnkù", meaning: "shorts", example: "夏天我穿短裤。", russian: "шорты" },
  { hanzi: "牛仔裤", pinyin: "niúzǎikù", meaning: "jeans", example: "我喜欢牛仔裤。", russian: "джинсы" },
  { hanzi: "衬衫", pinyin: "chènshān", meaning: "shirt", example: "这件衬衫不错。", russian: "рубашка" },
  { hanzi: "帽子", pinyin: "màozi", meaning: "hat", example: "帽子很好看。", russian: "шапка, кепка" },
  { hanzi: "连衣裙", pinyin: "liányīqún", meaning: "one-piece dress", example: "这条连衣裙很漂亮。", russian: "платье" },

  { hanzi: "哪儿", pinyin: "nǎr", meaning: "where", example: "银行在哪儿？", russian: "где" },
  { hanzi: "楼", pinyin: "lóu", meaning: "building, storey", example: "银行在三楼。", russian: "здание, этаж" },
  { hanzi: "怎么", pinyin: "zěnme", meaning: "how", example: "去银行怎么走？", russian: "как" },
  { hanzi: "走", pinyin: "zǒu", meaning: "walk, go", example: "我们走吧。", russian: "идти, ходить" },
  { hanzi: "路人", pinyin: "lùrén", meaning: "passerby", example: "路人帮我找银行。", russian: "прохожий" },
  { hanzi: "邮局", pinyin: "yóujú", meaning: "post office", example: "邮局在银行旁边。", russian: "почта" },
  { hanzi: "后边", pinyin: "hòubian", meaning: "back, behind", example: "学校在邮局后边。", russian: "сзади, позади" },
  { hanzi: "往", pinyin: "wǎng", meaning: "towards", example: "往前走。", russian: "в сторону, к" },
  { hanzi: "南边", pinyin: "nánbian", meaning: "south", example: "公园在南边。", russian: "юг, южная сторона" },
  { hanzi: "离", pinyin: "lí", meaning: "away from", example: "学校离银行很近。", russian: "от, на расстоянии от" },
  { hanzi: "这儿", pinyin: "zhèr", meaning: "here", example: "我在这儿。", russian: "здесь" },
  { hanzi: "对", pinyin: "duì", meaning: "right, correct", example: "你说得对。", russian: "правильно, верно" },
  { hanzi: "银行", pinyin: "yínháng", meaning: "bank", example: "银行在哪儿？", russian: "банк" },
  { hanzi: "附近", pinyin: "fùjìn", meaning: "vicinity, nearby", example: "附近有邮局吗？", russian: "рядом, поблизости" },
  { hanzi: "前边", pinyin: "qiánbian", meaning: "front", example: "银行在前边。", russian: "спереди, впереди" },
  { hanzi: "分钟", pinyin: "fēnzhōng", meaning: "minute", example: "走五分钟就到了。", russian: "минута" },
  { hanzi: "左右", pinyin: "zuǒyòu", meaning: "about", example: "十分钟左右。", russian: "примерно, около" },
  { hanzi: "东边", pinyin: "dōngbian", meaning: "east side", example: "银行在东边。", russian: "восточная сторона" },
  { hanzi: "西边", pinyin: "xībian", meaning: "west side", example: "邮局在西边。", russian: "западная сторона" },
  { hanzi: "北边", pinyin: "běibian", meaning: "north side", example: "学校在北边。", russian: "северная сторона" }
].map((item) => ({
  unit: "UNIT-1",
  ...item,
  russianExplanation: item.russianExplanation || makeChineseExplanation(item)
}));

window.CHINESE_WORDS = CHINESE_WORDS;// chinese.js
// Все слова относятся к UNIT-1.
// Карточка показывает: иероглиф, перевод, pinyin, meaning, example, example pinyin, example Russian, lexical explanation.

const CHINESE_PARTS = {
  "电": "электричество",
  "话": "речь, слова",
  "号": "номер, знак",
  "码": "код, цифровое обозначение",
  "手": "рука",
  "机": "машина, устройство",
  "多": "много",
  "少": "мало",
  "公": "общественный",
  "园": "сад, парк",
  "路": "дорога",
  "新": "новый",
  "地": "место, земля",
  "址": "местонахождение, адрес",
  "大": "большой",
  "学": "учёба, учиться",
  "寓": "жильё",
  "房": "дом, помещение",
  "间": "пространство, комната",
  "可": "можно",
  "以": "можно, с помощью",
  "给": "дать, передать",
  "打": "бить, делать действие рукой",
  "发": "отправлять",
  "件": "предмет, документ, вещь",
  "人": "человек",
  "收": "получать",
  "到": "дойти, прибыть",
  "谢": "благодарить",
  "箱": "ящик, коробка",
  "送": "посылать, доставлять",
  "短": "короткий",
  "信": "письмо, сообщение",
  "退": "отступать, выходить",
  "出": "выходить",
  "省": "провинция",
  "市": "город, рынок",
  "区": "район",
  "街": "улица",

  "二": "два",
  "月": "месяц, луна",
  "生": "рождаться, жизнь",
  "日": "день, солнце",
  "真": "настоящий, правда",
  "今": "нынешний",
  "天": "день, небо",
  "几": "сколько",
  "星": "звезда",
  "期": "период, срок",
  "我": "я",
  "们": "суффикс множественного числа",
  "吃": "есть, кушать",
  "饭": "еда, рис",
  "去": "идти, уходить",
  "厨": "кухня",
  "怎": "как",
  "么": "служебная часть вопросительных слов",
  "样": "вид, образ",
  "那": "тот, там",
  "里": "внутри, место",
  "中": "Китай, середина",
  "餐": "еда, приём пищи",
  "好": "хороший",
  "没": "нет, не иметь",
  "问": "спрашивать",
  "题": "тема, вопрос",
  "六": "шесть",
  "一": "один",
  "三": "три",
  "四": "четыре",
  "五": "пять",
  "跟": "с, вместе с",
  "见": "видеть, встречать",
  "面": "лицо, поверхность",
  "看": "смотреть, читать",
  "书": "книга",
  "上": "верх, идти на",
  "班": "смена, работа",
  "派": "группа, направление",
  "对": "пара, напротив, правильно",
  "七": "семь",
  "九": "девять",
  "年": "год",
  "昨": "вчерашний",
  "明": "светлый, следующий",
  "个": "счётное слово",
  "下": "низ, следующий",

  "周": "неделя, круг",
  "末": "конец",
  "有": "иметь, есть",
  "时": "время",
  "要": "хотеть, нужно",
  "爷": "дедушка",
  "计": "считать, планировать",
  "划": "планировать, чертить",
  "起": "подниматься, вместе",
  "影": "тень, изображение",
  "点": "точка, час",
  "半": "половина",
  "开": "открывать, начинать",
  "始": "начало",
  "院": "учреждение, двор",
  "门": "дверь",
  "口": "рот, вход",
  "太": "слишком, очень",
  "了": "служебная частица завершения действия",
  "朋": "друг",
  "友": "друг",
  "晚": "вечер, поздно",
  "事": "дело",
  "午": "полдень",
  "分": "минута, часть",
  "刻": "четверть часа, момент",
  "英": "английский, герой",
  "语": "язык, речь",
  "菜": "блюдо, овощ",
  "跑": "бежать",
  "步": "шаг",
  "写": "писать",
  "子": "суффикс существительного",
  "邮": "почта",
  "奶": "бабушка, молоко",
  "运": "двигаться, перевозить",
  "动": "двигаться",
  "音": "звук",
  "乐": "музыка, радость",
  "会": "собрание, уметь",
  "卡": "карточка",
  "博": "широкий, блог",
  "客": "гость",
  "游": "плавать, путешествовать",
  "泳": "плавание",
  "买": "покупать",
  "东": "восток",
  "西": "запад",
  "视": "смотреть",
  "比": "сравнивать",
  "赛": "соревнование",

  "售": "продавать",
  "货": "товар",
  "员": "работник, сотрудник",
  "衣": "одежда",
  "服": "одежда, служить",
  "条": "длинный предмет, счётное слово",
  "裙": "юбка",
  "来": "приходить",
  "这": "этот",
  "边": "сторона",
  "红": "красный",
  "蓝": "синий",
  "色": "цвет",
  "黑": "чёрный",
  "试": "пробовать, примерять",
  "错": "ошибка, плохой",
  "钱": "деньги",
  "百": "сто",
  "块": "кусок, юань",
  "便": "удобный, дешёвый",
  "宜": "подходящий",
  "价": "цена",
  "贵": "дорогой",
  "吧": "частица предложения",
  "店": "магазин",
  "装": "одежда, наряд",
  "场": "площадка, рынок",
  "远": "далеко",
  "裤": "брюки",
  "白": "белый",
  "名": "имя, известность",
  "购": "покупать",
  "物": "вещь",
  "心": "центр, сердце",
  "双": "пара",
  "鞋": "обувь",
  "每": "каждый",
  "很": "очень",
  "超": "супер, сверх",
  "绿": "зелёный",
  "黄": "жёлтый",
  "毛": "шерсть",
  "围": "оборачивать",
  "巾": "платок, ткань",
  "牛": "корова",
  "仔": "молодой, деталь слова",
  "衬": "подкладка, рубашка",
  "衫": "рубашка",
  "帽": "шапка",
  "连": "соединять",

  "哪": "какой, где",
  "儿": "суффикс разговорной речи",
  "楼": "здание, этаж",
  "走": "идти",
  "后": "задний, после",
  "往": "в сторону",
  "南": "юг",
  "离": "от, расстояние",
  "银": "серебро",
  "行": "банк, ряд, идти",
  "近": "близко",
  "前": "передний",
  "钟": "час, колокол",
  "左": "лево",
  "右": "право",
  "北": "север"
};

function makeChineseExplanation(item) {
  const hanzi = String(item.hanzi || "");
  const chars = [...hanzi].filter((char) => CHINESE_PARTS[char]);

  if (!chars.length) {
    return `${hanzi} — китайское слово. Значение: ${item.russian || item.meaning || ""}.`;
  }

  const parts = chars
    .map((char) => `${char} — ${CHINESE_PARTS[char]}`)
    .join(", ");

  return `${parts}. Вместе ${hanzi} значит: ${item.russian || item.meaning || ""}.`;
}

const CHINESE_WORDS = [
  {
    hanzi: "电话",
    pinyin: "diànhuà",
    meaning: "telephone",
    example: "我有电话。",
    examplePinyin: "Wǒ yǒu diànhuà.",
    exampleRussian: "У меня есть телефон.",
    russian: "телефон"
  },
  {
    hanzi: "号码",
    pinyin: "hàomǎ",
    meaning: "number, code",
    example: "你的号码是多少？",
    examplePinyin: "Nǐ de hàomǎ shì duōshao?",
    exampleRussian: "Какой у тебя номер?",
    russian: "номер, код"
  },
  {
    hanzi: "手机",
    pinyin: "shǒujī",
    meaning: "mobile phone",
    example: "这是我的手机。",
    examplePinyin: "Zhè shì wǒ de shǒujī.",
    exampleRussian: "Это мой мобильный телефон.",
    russian: "мобильный телефон"
  },
  {
    hanzi: "多少",
    pinyin: "duōshao",
    meaning: "what, how many/much",
    example: "多少钱？",
    examplePinyin: "Duōshao qián?",
    exampleRussian: "Сколько стоит?",
    russian: "сколько"
  },
  {
    hanzi: "公园",
    pinyin: "gōngyuán",
    meaning: "park",
    example: "公园在附近。",
    examplePinyin: "Gōngyuán zài fùjìn.",
    exampleRussian: "Парк находится рядом.",
    russian: "парк"
  },
  {
    hanzi: "路",
    pinyin: "lù",
    meaning: "road",
    example: "这条路很长。",
    examplePinyin: "Zhè tiáo lù hěn cháng.",
    exampleRussian: "Эта дорога очень длинная.",
    russian: "дорога"
  },
  {
    hanzi: "号",
    pinyin: "hào",
    meaning: "number, date",
    example: "一号。",
    examplePinyin: "Yī hào.",
    exampleRussian: "Первое число / номер один.",
    russian: "номер, дата"
  },
  {
    hanzi: "新",
    pinyin: "xīn",
    meaning: "new",
    example: "这是新手机。",
    examplePinyin: "Zhè shì xīn shǒujī.",
    exampleRussian: "Это новый мобильный телефон.",
    russian: "новый"
  },
  {
    hanzi: "地址",
    pinyin: "dìzhǐ",
    meaning: "address",
    example: "你的地址是什么？",
    examplePinyin: "Nǐ de dìzhǐ shì shénme?",
    exampleRussian: "Какой у тебя адрес?",
    russian: "адрес"
  },
  {
    hanzi: "大学",
    pinyin: "dàxué",
    meaning: "university",
    example: "我在大学学习。",
    examplePinyin: "Wǒ zài dàxué xuéxí.",
    exampleRussian: "Я учусь в университете.",
    russian: "университет"
  },
  {
    hanzi: "公寓",
    pinyin: "gōngyù",
    meaning: "block of flats, apartment building",
    example: "我住在公寓。",
    examplePinyin: "Wǒ zhù zài gōngyù.",
    exampleRussian: "Я живу в квартире / жилом доме.",
    russian: "квартира, жилой дом"
  },
  {
    hanzi: "房间",
    pinyin: "fángjiān",
    meaning: "room",
    example: "我的房间很大。",
    examplePinyin: "Wǒ de fángjiān hěn dà.",
    exampleRussian: "Моя комната очень большая.",
    russian: "комната"
  },
  {
    hanzi: "可以",
    pinyin: "kěyǐ",
    meaning: "may, can",
    example: "我可以去吗？",
    examplePinyin: "Wǒ kěyǐ qù ma?",
    exampleRussian: "Можно мне пойти?",
    russian: "можно, мочь"
  },
  {
    hanzi: "给",
    pinyin: "gěi",
    meaning: "give, to",
    example: "我给你电话。",
    examplePinyin: "Wǒ gěi nǐ diànhuà.",
    exampleRussian: "Я дам тебе телефон / номер.",
    russian: "дать, для, к"
  },
  {
    hanzi: "打电话",
    pinyin: "dǎ diànhuà",
    meaning: "make a phone call",
    example: "我给妈妈打电话。",
    examplePinyin: "Wǒ gěi māma dǎ diànhuà.",
    exampleRussian: "Я звоню маме.",
    russian: "звонить по телефону"
  },
  {
    hanzi: "发件人",
    pinyin: "fājiànrén",
    meaning: "sender",
    example: "发件人是谁？",
    examplePinyin: "Fājiànrén shì shéi?",
    exampleRussian: "Кто отправитель?",
    russian: "отправитель"
  },
  {
    hanzi: "收到",
    pinyin: "shōudào",
    meaning: "receive",
    example: "我收到短信。",
    examplePinyin: "Wǒ shōudào duǎnxìn.",
    exampleRussian: "Я получил SMS.",
    russian: "получать"
  },
  {
    hanzi: "谢谢",
    pinyin: "xièxie",
    meaning: "thank you",
    example: "谢谢你！",
    examplePinyin: "Xièxie nǐ!",
    exampleRussian: "Спасибо тебе!",
    russian: "спасибо"
  },
  {
    hanzi: "收件箱",
    pinyin: "shōujiànxiāng",
    meaning: "inbox",
    example: "收件箱里有邮件。",
    examplePinyin: "Shōujiànxiāng lǐ yǒu yóujiàn.",
    exampleRussian: "Во входящих есть письмо.",
    russian: "входящие сообщения"
  },
  {
    hanzi: "发送",
    pinyin: "fāsòng",
    meaning: "send",
    example: "我发送短信。",
    examplePinyin: "Wǒ fāsòng duǎnxìn.",
    exampleRussian: "Я отправляю SMS.",
    russian: "отправлять"
  },
  {
    hanzi: "短信",
    pinyin: "duǎnxìn",
    meaning: "message",
    example: "我收到短信。",
    examplePinyin: "Wǒ shōudào duǎnxìn.",
    exampleRussian: "Я получил SMS.",
    russian: "сообщение, SMS"
  },
  {
    hanzi: "退出",
    pinyin: "tuìchū",
    meaning: "exit, go back",
    example: "请退出。",
    examplePinyin: "Qǐng tuìchū.",
    exampleRussian: "Пожалуйста, выйдите.",
    russian: "выйти, вернуться"
  },
  {
    hanzi: "省",
    pinyin: "shěng",
    meaning: "province",
    example: "这是一个省。",
    examplePinyin: "Zhè shì yí gè shěng.",
    exampleRussian: "Это провинция.",
    russian: "провинция"
  },
  {
    hanzi: "市",
    pinyin: "shì",
    meaning: "city",
    example: "我住在阿拉木图市。",
    examplePinyin: "Wǒ zhù zài Ālāmùtú shì.",
    exampleRussian: "Я живу в городе Алматы.",
    russian: "город"
  },
  {
    hanzi: "区",
    pinyin: "qū",
    meaning: "district",
    example: "这个区很大。",
    examplePinyin: "Zhège qū hěn dà.",
    exampleRussian: "Этот район очень большой.",
    russian: "район"
  },
  {
    hanzi: "街",
    pinyin: "jiē",
    meaning: "street",
    example: "这条街很长。",
    examplePinyin: "Zhè tiáo jiē hěn cháng.",
    exampleRussian: "Эта улица очень длинная.",
    russian: "улица"
  },

  {
    hanzi: "二月",
    pinyin: "èryuè",
    meaning: "February",
    example: "我的生日在二月。",
    examplePinyin: "Wǒ de shēngrì zài èryuè.",
    exampleRussian: "Мой день рождения в феврале.",
    russian: "февраль"
  },
  {
    hanzi: "月",
    pinyin: "yuè",
    meaning: "month",
    example: "一月是第一个月。",
    examplePinyin: "Yīyuè shì dì yī gè yuè.",
    exampleRussian: "Январь — первый месяц.",
    russian: "месяц"
  },
  {
    hanzi: "生日",
    pinyin: "shēngrì",
    meaning: "birthday",
    example: "今天是我的生日。",
    examplePinyin: "Jīntiān shì wǒ de shēngrì.",
    exampleRussian: "Сегодня мой день рождения.",
    russian: "день рождения"
  },
  {
    hanzi: "真的",
    pinyin: "zhēn de",
    meaning: "really",
    example: "真的吗？",
    examplePinyin: "Zhēn de ma?",
    exampleRussian: "Правда?",
    russian: "правда, действительно"
  },
  {
    hanzi: "今天",
    pinyin: "jīntiān",
    meaning: "today",
    example: "今天我学习中文。",
    examplePinyin: "Jīntiān wǒ xuéxí Zhōngwén.",
    exampleRussian: "Сегодня я изучаю китайский язык.",
    russian: "сегодня"
  },
  {
    hanzi: "几",
    pinyin: "jǐ",
    meaning: "how many",
    example: "今天几号？",
    examplePinyin: "Jīntiān jǐ hào?",
    exampleRussian: "Какое сегодня число?",
    russian: "сколько, который"
  },
  {
    hanzi: "星期天",
    pinyin: "xīngqītiān",
    meaning: "Sunday spoken",
    example: "星期天我休息。",
    examplePinyin: "Xīngqītiān wǒ xiūxi.",
    exampleRussian: "В воскресенье я отдыхаю.",
    russian: "воскресенье"
  },
  {
    hanzi: "星期",
    pinyin: "xīngqī",
    meaning: "week",
    example: "这个星期我很忙。",
    examplePinyin: "Zhège xīngqī wǒ hěn máng.",
    exampleRussian: "На этой неделе я очень занят.",
    russian: "неделя"
  },
  {
    hanzi: "我们",
    pinyin: "wǒmen",
    meaning: "we, us",
    example: "我们去学校。",
    examplePinyin: "Wǒmen qù xuéxiào.",
    exampleRussian: "Мы идём в школу.",
    russian: "мы"
  },
  {
    hanzi: "吃饭",
    pinyin: "chīfàn",
    meaning: "have a meal",
    example: "我们一起吃饭。",
    examplePinyin: "Wǒmen yìqǐ chīfàn.",
    exampleRussian: "Мы вместе кушаем.",
    russian: "кушать, есть"
  },
  {
    hanzi: "吃",
    pinyin: "chī",
    meaning: "eat",
    example: "我吃饭。",
    examplePinyin: "Wǒ chīfàn.",
    exampleRussian: "Я кушаю.",
    russian: "есть, кушать"
  },
  {
    hanzi: "去",
    pinyin: "qù",
    meaning: "go",
    example: "我去大学。",
    examplePinyin: "Wǒ qù dàxué.",
    exampleRussian: "Я иду в университет.",
    russian: "идти, ехать"
  },
  {
    hanzi: "厨房",
    pinyin: "chúfáng",
    meaning: "kitchen",
    example: "妈妈在厨房。",
    examplePinyin: "Māma zài chúfáng.",
    exampleRussian: "Мама на кухне.",
    russian: "кухня"
  },
  {
    hanzi: "怎么样",
    pinyin: "zěnmeyàng",
    meaning: "how about",
    example: "这个怎么样？",
    examplePinyin: "Zhège zěnmeyàng?",
    exampleRussian: "Как насчёт этого?",
    russian: "как насчет, как"
  },
  {
    hanzi: "那里",
    pinyin: "nàli",
    meaning: "there",
    example: "他在那里。",
    examplePinyin: "Tā zài nàli.",
    exampleRussian: "Он там.",
    russian: "там"
  },
  {
    hanzi: "中餐",
    pinyin: "zhōngcān",
    meaning: "Chinese food",
    example: "我喜欢中餐。",
    examplePinyin: "Wǒ xǐhuan zhōngcān.",
    exampleRussian: "Мне нравится китайская еда.",
    russian: "китайская еда"
  },
  {
    hanzi: "餐",
    pinyin: "cān",
    meaning: "cuisine, meal",
    example: "这餐很好吃。",
    examplePinyin: "Zhè cān hěn hǎochī.",
    exampleRussian: "Эта еда очень вкусная.",
    russian: "еда, прием пищи"
  },
  {
    hanzi: "好吃",
    pinyin: "hǎochī",
    meaning: "tasty",
    example: "这个菜很好吃。",
    examplePinyin: "Zhège cài hěn hǎochī.",
    exampleRussian: "Это блюдо очень вкусное.",
    russian: "вкусный"
  },
  {
    hanzi: "没问题",
    pinyin: "méi wèntí",
    meaning: "no problem",
    example: "没问题！",
    examplePinyin: "Méi wèntí!",
    exampleRussian: "Нет проблем!",
    russian: "нет проблем"
  },
  {
    hanzi: "六月",
    pinyin: "liùyuè",
    meaning: "June",
    example: "六月天气很好。",
    examplePinyin: "Liùyuè tiānqì hěn hǎo.",
    exampleRussian: "В июне погода хорошая.",
    russian: "июнь"
  },
  {
    hanzi: "日",
    pinyin: "rì",
    meaning: "date written",
    example: "六月一日。",
    examplePinyin: "Liùyuè yī rì.",
    exampleRussian: "Первое июня.",
    russian: "день, число"
  },
  {
    hanzi: "星期日",
    pinyin: "xīngqīrì",
    meaning: "Sunday written",
    example: "星期日我休息。",
    examplePinyin: "Xīngqīrì wǒ xiūxi.",
    exampleRussian: "В воскресенье я отдыхаю.",
    russian: "воскресенье"
  },
  {
    hanzi: "星期一",
    pinyin: "xīngqīyī",
    meaning: "Monday",
    example: "星期一我上课。",
    examplePinyin: "Xīngqīyī wǒ shàngkè.",
    exampleRussian: "В понедельник у меня занятия.",
    russian: "понедельник"
  },
  {
    hanzi: "星期二",
    pinyin: "xīngqī'èr",
    meaning: "Tuesday",
    example: "星期二我学习。",
    examplePinyin: "Xīngqī'èr wǒ xuéxí.",
    exampleRussian: "Во вторник я учусь.",
    russian: "вторник"
  },
  {
    hanzi: "星期三",
    pinyin: "xīngqīsān",
    meaning: "Wednesday",
    example: "星期三我去学校。",
    examplePinyin: "Xīngqīsān wǒ qù xuéxiào.",
    exampleRussian: "В среду я иду в школу.",
    russian: "среда"
  },
  {
    hanzi: "星期四",
    pinyin: "xīngqīsì",
    meaning: "Thursday",
    example: "星期四我很忙。",
    examplePinyin: "Xīngqīsì wǒ hěn máng.",
    exampleRussian: "В четверг я очень занят.",
    russian: "четверг"
  },
  {
    hanzi: "星期五",
    pinyin: "xīngqīwǔ",
    meaning: "Friday",
    example: "星期五我看电影。",
    examplePinyin: "Xīngqīwǔ wǒ kàn diànyǐng.",
    exampleRussian: "В пятницу я смотрю фильм.",
    russian: "пятница"
  },
  {
    hanzi: "星期六",
    pinyin: "xīngqīliù",
    meaning: "Saturday",
    example: "星期六我休息。",
    examplePinyin: "Xīngqīliù wǒ xiūxi.",
    exampleRussian: "В субботу я отдыхаю.",
    russian: "суббота"
  },
  {
    hanzi: "打",
    pinyin: "dǎ",
    meaning: "play ball game with hands",
    example: "我打篮球。",
    examplePinyin: "Wǒ dǎ lánqiú.",
    exampleRussian: "Я играю в баскетбол.",
    russian: "играть, бить"
  },
  {
    hanzi: "跟",
    pinyin: "gēn",
    meaning: "with",
    example: "我跟朋友去。",
    examplePinyin: "Wǒ gēn péngyou qù.",
    exampleRussian: "Я иду с другом.",
    russian: "с, вместе с"
  },
  {
    hanzi: "见面",
    pinyin: "jiànmiàn",
    meaning: "meet up",
    example: "我们明天见面。",
    examplePinyin: "Wǒmen míngtiān jiànmiàn.",
    exampleRussian: "Мы встретимся завтра.",
    russian: "встречаться"
  },
  {
    hanzi: "看",
    pinyin: "kàn",
    meaning: "read, see",
    example: "我看书。",
    examplePinyin: "Wǒ kàn shū.",
    exampleRussian: "Я читаю книгу.",
    russian: "смотреть, читать"
  },
  {
    hanzi: "书",
    pinyin: "shū",
    meaning: "book",
    example: "这是我的书。",
    examplePinyin: "Zhè shì wǒ de shū.",
    exampleRussian: "Это моя книга.",
    russian: "книга"
  },
  {
    hanzi: "上班",
    pinyin: "shàngbān",
    meaning: "go to work",
    example: "爸爸去上班。",
    examplePinyin: "Bàba qù shàngbān.",
    exampleRussian: "Папа идёт на работу.",
    russian: "идти на работу"
  },
  {
    hanzi: "学",
    pinyin: "xué",
    meaning: "study, learn",
    example: "我学中文。",
    examplePinyin: "Wǒ xué Zhōngwén.",
    exampleRussian: "Я учу китайский язык.",
    russian: "учиться, изучать"
  },
  {
    hanzi: "派对",
    pinyin: "pàiduì",
    meaning: "party",
    example: "我们去派对。",
    examplePinyin: "Wǒmen qù pàiduì.",
    exampleRussian: "Мы идём на вечеринку.",
    russian: "вечеринка"
  },
  {
    hanzi: "一月",
    pinyin: "yīyuè",
    meaning: "January",
    example: "一月很冷。",
    examplePinyin: "Yīyuè hěn lěng.",
    exampleRussian: "В январе очень холодно.",
    russian: "январь"
  },
  {
    hanzi: "五月",
    pinyin: "wǔyuè",
    meaning: "May",
    example: "五月天气很好。",
    examplePinyin: "Wǔyuè tiānqì hěn hǎo.",
    exampleRussian: "В мае погода хорошая.",
    russian: "май"
  },
  {
    hanzi: "七月",
    pinyin: "qīyuè",
    meaning: "July",
    example: "七月很热。",
    examplePinyin: "Qīyuè hěn rè.",
    exampleRussian: "В июле очень жарко.",
    russian: "июль"
  },
  {
    hanzi: "九月",
    pinyin: "jiǔyuè",
    meaning: "September",
    example: "九月开学。",
    examplePinyin: "Jiǔyuè kāixué.",
    exampleRussian: "В сентябре начинается учёба.",
    russian: "сентябрь"
  },
  {
    hanzi: "去年",
    pinyin: "qùnián",
    meaning: "last year",
    example: "去年我学习中文。",
    examplePinyin: "Qùnián wǒ xuéxí Zhōngwén.",
    exampleRussian: "В прошлом году я изучал китайский.",
    russian: "прошлый год"
  },
  {
    hanzi: "今年",
    pinyin: "jīnnián",
    meaning: "this year",
    example: "今年是2026年。",
    examplePinyin: "Jīnnián shì èr líng èr liù nián.",
    exampleRussian: "Этот год — 2026.",
    russian: "этот год"
  },
  {
    hanzi: "明年",
    pinyin: "míngnián",
    meaning: "next year",
    example: "明年我去中国。",
    examplePinyin: "Míngnián wǒ qù Zhōngguó.",
    exampleRussian: "В следующем году я поеду в Китай.",
    russian: "следующий год"
  },
  {
    hanzi: "昨天",
    pinyin: "zuótiān",
    meaning: "yesterday",
    example: "昨天我很忙。",
    examplePinyin: "Zuótiān wǒ hěn máng.",
    exampleRussian: "Вчера я был очень занят.",
    russian: "вчера"
  },
  {
    hanzi: "明天",
    pinyin: "míngtiān",
    meaning: "tomorrow",
    example: "明天见！",
    examplePinyin: "Míngtiān jiàn!",
    exampleRussian: "Увидимся завтра!",
    russian: "завтра"
  },
  {
    hanzi: "上个",
    pinyin: "shàngge",
    meaning: "last",
    example: "上个星期。",
    examplePinyin: "Shàng ge xīngqī.",
    exampleRussian: "Прошлая неделя.",
    russian: "прошлый"
  },
  {
    hanzi: "这个",
    pinyin: "zhège",
    meaning: "this",
    example: "这个很好。",
    examplePinyin: "Zhège hěn hǎo.",
    exampleRussian: "Это очень хорошо.",
    russian: "этот"
  },
  {
    hanzi: "下个",
    pinyin: "xiàge",
    meaning: "next",
    example: "下个星期。",
    examplePinyin: "Xià ge xīngqī.",
    exampleRussian: "Следующая неделя.",
    russian: "следующий"
  }
];

const EXTRA_CHINESE_WORDS = [
  ["周末", "zhōumò", "weekend", "周末我看电影。", "Zhōumò wǒ kàn diànyǐng.", "На выходных я смотрю фильм.", "выходные"],
  ["有", "yǒu", "have", "我有时间。", "Wǒ yǒu shíjiān.", "У меня есть время.", "иметь, есть"],
  ["时间", "shíjiān", "time", "你有时间吗？", "Nǐ yǒu shíjiān ma?", "У тебя есть время?", "время"],
  ["要", "yào", "want", "我要去电影院。", "Wǒ yào qù diànyǐngyuàn.", "Я хочу пойти в кинотеатр.", "хотеть, нужно"],
  ["爷爷", "yéye", "grandfather", "我爷爷很好。", "Wǒ yéye hěn hǎo.", "Мой дедушка очень хороший.", "дедушка"],
  ["计划", "jìhuà", "plan", "你有什么计划？", "Nǐ yǒu shénme jìhuà?", "Какие у тебя планы?", "план"],
  ["没有", "méiyǒu", "not have", "我没有时间。", "Wǒ méiyǒu shíjiān.", "У меня нет времени.", "нет, не иметь"],
  ["一起", "yìqǐ", "together", "我们一起去吧。", "Wǒmen yìqǐ qù ba.", "Пойдём вместе.", "вместе"],
  ["电影", "diànyǐng", "movie, film", "我想看电影。", "Wǒ xiǎng kàn diànyǐng.", "Я хочу посмотреть фильм.", "фильм, кино"],
  ["几点", "jǐ diǎn", "what time", "电影几点开始？", "Diànyǐng jǐ diǎn kāishǐ?", "Во сколько начинается фильм?", "во сколько"],
  ["点", "diǎn", "o'clock", "三点。", "Sān diǎn.", "Три часа.", "час, часов"],
  ["半", "bàn", "half", "三点半。", "Sān diǎn bàn.", "Половина четвёртого / 3:30.", "половина"],
  ["开始", "kāishǐ", "start", "电影开始了。", "Diànyǐng kāishǐ le.", "Фильм начался.", "начинать"],
  ["电影院", "diànyǐngyuàn", "cinema", "电影院在哪儿？", "Diànyǐngyuàn zài nǎr?", "Где находится кинотеатр?", "кинотеатр"],
  ["门口", "ménkǒu", "entrance, doorway", "我在门口等你。", "Wǒ zài ménkǒu děng nǐ.", "Я жду тебя у входа.", "вход, у двери"],
  ["见", "jiàn", "see, meet", "明天见！", "Míngtiān jiàn!", "Увидимся завтра!", "видеть, встречать"],
  ["太", "tài", "very, too", "太好了！", "Tài hǎo le!", "Очень хорошо!", "слишком, очень"],
  ["了", "le", "particle", "电影开始了。", "Diànyǐng kāishǐ le.", "Фильм начался.", "частица"],
  ["朋友", "péngyou", "friend", "他是我的朋友。", "Tā shì wǒ de péngyou.", "Он мой друг.", "друг"],
  ["晚上", "wǎnshang", "evening", "晚上我看电影。", "Wǎnshang wǒ kàn diànyǐng.", "Вечером я смотрю фильм.", "вечер"],
  ["事", "shì", "thing, matter", "我有事。", "Wǒ yǒu shì.", "У меня есть дела.", "дело"],
  ["上午", "shàngwǔ", "morning", "上午我学习。", "Shàngwǔ wǒ xuéxí.", "Утром я учусь.", "утро, до обеда"],
  ["分", "fēn", "minute", "五分。", "Wǔ fēn.", "Пять минут.", "минута"],
  ["刻", "kè", "quarter of an hour", "三点一刻。", "Sān diǎn yí kè.", "3:15.", "четверть часа"],
  ["英语", "yīngyǔ", "English", "我学习英语。", "Wǒ xuéxí Yīngyǔ.", "Я изучаю английский язык.", "английский язык"],
  ["中午", "zhōngwǔ", "noon", "中午我吃饭。", "Zhōngwǔ wǒ chīfàn.", "В полдень я кушаю.", "полдень"],
  ["菜", "cài", "food, dish", "这个菜很好吃。", "Zhège cài hěn hǎochī.", "Это блюдо очень вкусное.", "блюдо, еда"],
  ["下午", "xiàwǔ", "afternoon", "下午我跑步。", "Xiàwǔ wǒ pǎobù.", "После обеда я бегаю.", "после обеда"],
  ["跑步", "pǎobù", "jog", "我喜欢跑步。", "Wǒ xǐhuan pǎobù.", "Мне нравится бегать.", "бегать"],
  ["写", "xiě", "write", "我写电子邮件。", "Wǒ xiě diànzǐ yóujiàn.", "Я пишу электронное письмо.", "писать"],
  ["电子邮件", "diànzǐ yóujiàn", "email", "我写电子邮件。", "Wǒ xiě diànzǐ yóujiàn.", "Я пишу электронное письмо.", "электронная почта"],
  ["唱歌", "chànggē", "sing a song", "她喜欢唱歌。", "Tā xǐhuan chànggē.", "Ей нравится петь.", "петь"],
  ["奶奶", "nǎinai", "grandmother", "我奶奶很好。", "Wǒ nǎinai hěn hǎo.", "Моя бабушка очень хорошая.", "бабушка"],
  ["到", "dào", "get to, arrive", "我到学校了。", "Wǒ dào xuéxiào le.", "Я прибыл в школу.", "прибывать, доходить"],
  ["运动", "yùndòng", "sports", "我喜欢运动。", "Wǒ xǐhuan yùndòng.", "Мне нравится спорт.", "спорт"],
  ["晚饭", "wǎnfàn", "dinner", "晚上我吃晚饭。", "Wǎnshang wǒ chī wǎnfàn.", "Вечером я ужинаю.", "ужин"],
  ["音乐", "yīnyuè", "music", "我听音乐。", "Wǒ tīng yīnyuè.", "Я слушаю музыку.", "музыка"],
  ["听", "tīng", "listen", "我听音乐。", "Wǒ tīng yīnyuè.", "Я слушаю музыку.", "слушать"],
  ["音乐会", "yīnyuèhuì", "concert", "我们去音乐会。", "Wǒmen qù yīnyuèhuì.", "Мы идём на концерт.", "концерт"],
  ["生日卡", "shēngrìkǎ", "birthday card", "我写生日卡。", "Wǒ xiě shēngrìkǎ.", "Я пишу открытку на день рождения.", "открытка на день рождения"],
  ["博客", "bókè", "blog", "我写博客。", "Wǒ xiě bókè.", "Я пишу блог.", "блог"],
  ["游泳", "yóuyǒng", "swim", "我喜欢游泳。", "Wǒ xǐhuan yóuyǒng.", "Мне нравится плавать.", "плавать"],
  ["买", "mǎi", "buy", "我买东西。", "Wǒ mǎi dōngxi.", "Я покупаю вещи.", "покупать"],
  ["东西", "dōngxi", "thing", "我买东西。", "Wǒ mǎi dōngxi.", "Я покупаю вещи.", "вещь, вещи"],
  ["电视", "diànshì", "television", "我看电视。", "Wǒ kàn diànshì.", "Я смотрю телевизор.", "телевизор"],
  ["比赛", "bǐsài", "competition, match", "我看比赛。", "Wǒ kàn bǐsài.", "Я смотрю матч.", "соревнование, матч"],

  ["售货员", "shòuhuòyuán", "shop assistant", "售货员很热情。", "Shòuhuòyuán hěn rèqíng.", "Продавец очень приветливый.", "продавец"],
  ["衣服", "yīfu", "clothes", "这件衣服很好看。", "Zhè jiàn yīfu hěn hǎokàn.", "Эта одежда красивая.", "одежда"],
  ["条", "tiáo", "measure word", "一条裙子。", "Yì tiáo qúnzi.", "Одна юбка.", "счетное слово"],
  ["裙子", "qúnzi", "skirt", "这条裙子很漂亮。", "Zhè tiáo qúnzi hěn piàoliang.", "Эта юбка очень красивая.", "юбка"],
  ["来", "lái", "come", "你来这边。", "Nǐ lái zhèbian.", "Иди сюда.", "приходить"],
  ["这边", "zhèbian", "this way", "请来这边。", "Qǐng lái zhèbian.", "Пожалуйста, идите сюда.", "сюда, в эту сторону"],
  ["红", "hóng", "red", "我喜欢红色。", "Wǒ xǐhuan hóngsè.", "Мне нравится красный цвет.", "красный"],
  ["蓝色", "lánsè", "blue", "蓝色衣服很好看。", "Lánsè yīfu hěn hǎokàn.", "Синяя одежда красивая.", "синий"],
  ["黑色", "hēisè", "black", "我买黑色裤子。", "Wǒ mǎi hēisè kùzi.", "Я покупаю чёрные брюки.", "черный"],
  ["好看", "hǎokàn", "good-looking", "这件衣服很好看。", "Zhè jiàn yīfu hěn hǎokàn.", "Эта одежда красивая.", "красивый"],
  ["试", "shì", "try", "我可以试吗？", "Wǒ kěyǐ shì ma?", "Можно примерить?", "примерять"],
  ["不错", "bùcuò", "not bad", "这件衣服不错。", "Zhè jiàn yīfu bùcuò.", "Эта одежда неплохая.", "неплохо"],
  ["钱", "qián", "money", "我没有钱。", "Wǒ méiyǒu qián.", "У меня нет денег.", "деньги"],
  ["百", "bǎi", "hundred", "一百块。", "Yì bǎi kuài.", "Сто юаней.", "сто"],
  ["块", "kuài", "yuan", "这件衣服一百块。", "Zhè jiàn yīfu yì bǎi kuài.", "Эта одежда стоит сто юаней.", "юань"],
  ["便宜", "piányi", "cheap", "这个很便宜。", "Zhège hěn piányi.", "Это очень дешево.", "дешевый"],
  ["一点儿", "yìdiǎnr", "a little", "便宜一点儿吧。", "Piányi yìdiǎnr ba.", "Сделайте немного дешевле.", "немного"],
  ["价钱", "jiàqian", "price", "价钱贵吗？", "Jiàqian guì ma?", "Цена дорогая?", "цена"],
  ["贵", "guì", "expensive", "这条裙子很贵。", "Zhè tiáo qúnzi hěn guì.", "Эта юбка очень дорогая.", "дорогой"],
  ["吧", "ba", "particle", "我们走吧。", "Wǒmen zǒu ba.", "Пойдём.", "частица предложения"],
  ["书店", "shūdiàn", "bookshop", "书店在前边。", "Shūdiàn zài qiánbian.", "Книжный магазин впереди.", "книжный магазин"],
  ["服装市场", "fúzhuāng shìchǎng", "clothes market", "我们去服装市场。", "Wǒmen qù fúzhuāng shìchǎng.", "Мы идём на рынок одежды.", "рынок одежды"],
  ["远", "yuǎn", "far away", "商店很远。", "Shāngdiàn hěn yuǎn.", "Магазин далеко.", "далеко"],
  ["裤子", "kùzi", "trousers", "我买裤子。", "Wǒ mǎi kùzi.", "Я покупаю брюки.", "брюки"],
  ["T恤", "tīxù", "T-shirt", "这件T恤很好看。", "Zhè jiàn tīxù hěn hǎokàn.", "Эта футболка красивая.", "футболка"],
  ["白色", "báisè", "white", "我喜欢白色。", "Wǒ xǐhuan báisè.", "Мне нравится белый цвет.", "белый"],
  ["有名", "yǒumíng", "famous", "这个商店很有名。", "Zhège shāngdiàn hěn yǒumíng.", "Этот магазин известный.", "известный"],
  ["购物中心", "gòuwù zhōngxīn", "shopping centre", "购物中心很大。", "Gòuwù zhōngxīn hěn dà.", "Торговый центр большой.", "торговый центр"],
  ["这里", "zhèlǐ", "here", "这里有很多衣服。", "Zhèlǐ yǒu hěn duō yīfu.", "Здесь много одежды.", "здесь"],
  ["双", "shuāng", "pair", "一双鞋。", "Yì shuāng xié.", "Одна пара обуви.", "пара"],
  ["鞋", "xié", "shoes", "我买一双鞋。", "Wǒ mǎi yì shuāng xié.", "Я покупаю одну пару обуви.", "обувь"],
  ["件", "jiàn", "item, piece", "一件大衣。", "Yí jiàn dàyī.", "Одно пальто.", "счетное слово для одежды"],
  ["大衣", "dàyī", "coat", "这件大衣很贵。", "Zhè jiàn dàyī hěn guì.", "Это пальто очень дорогое.", "пальто"],
  ["每", "měi", "every, each", "每件衣服都很好看。", "Měi jiàn yīfu dōu hěn hǎokàn.", "Каждая одежда красивая.", "каждый"],
  ["很多", "hěn duō", "a lot of", "这里有很多衣服。", "Zhèlǐ yǒu hěn duō yīfu.", "Здесь много одежды.", "много"],
  ["超市", "chāoshì", "supermarket", "超市在附近。", "Chāoshì zài fùjìn.", "Супермаркет находится рядом.", "супермаркет"],
  ["绿色", "lǜsè", "green", "绿色毛衣很好看。", "Lǜsè máoyī hěn hǎokàn.", "Зелёный свитер красивый.", "зеленый"],
  ["黄色", "huángsè", "yellow", "黄色围巾很漂亮。", "Huángsè wéijīn hěn piàoliang.", "Жёлтый шарф очень красивый.", "желтый"],
  ["毛衣", "máoyī", "sweater", "我买毛衣。", "Wǒ mǎi máoyī.", "Я покупаю свитер.", "свитер"],
  ["围巾", "wéijīn", "scarf", "这条围巾很便宜。", "Zhè tiáo wéijīn hěn piányi.", "Этот шарф очень дешёвый.", "шарф"],
  ["短裤", "duǎnkù", "shorts", "夏天我穿短裤。", "Xiàtiān wǒ chuān duǎnkù.", "Летом я ношу шорты.", "шорты"],
  ["牛仔裤", "niúzǎikù", "jeans", "我喜欢牛仔裤。", "Wǒ xǐhuan niúzǎikù.", "Мне нравятся джинсы.", "джинсы"],
  ["衬衫", "chènshān", "shirt", "这件衬衫不错。", "Zhè jiàn chènshān bùcuò.", "Эта рубашка неплохая.", "рубашка"],
  ["帽子", "màozi", "hat", "帽子很好看。", "Màozi hěn hǎokàn.", "Шапка красивая.", "шапка, кепка"],
  ["连衣裙", "liányīqún", "one-piece dress", "这条连衣裙很漂亮。", "Zhè tiáo liányīqún hěn piàoliang.", "Это платье очень красивое.", "платье"],

  ["哪儿", "nǎr", "where", "银行在哪儿？", "Yínháng zài nǎr?", "Где находится банк?", "где"],
  ["楼", "lóu", "building, storey", "银行在三楼。", "Yínháng zài sān lóu.", "Банк находится на третьем этаже.", "здание, этаж"],
  ["怎么", "zěnme", "how", "去银行怎么走？", "Qù yínháng zěnme zǒu?", "Как пройти в банк?", "как"],
  ["走", "zǒu", "walk, go", "我们走吧。", "Wǒmen zǒu ba.", "Пойдём.", "идти, ходить"],
  ["路人", "lùrén", "passerby", "路人帮我找银行。", "Lùrén bāng wǒ zhǎo yínháng.", "Прохожий помог мне найти банк.", "прохожий"],
  ["邮局", "yóujú", "post office", "邮局在银行旁边。", "Yóujú zài yínháng pángbiān.", "Почта находится рядом с банком.", "почта"],
  ["后边", "hòubian", "back, behind", "学校在邮局后边。", "Xuéxiào zài yóujú hòubian.", "Школа находится позади почты.", "сзади, позади"],
  ["往", "wǎng", "towards", "往前走。", "Wǎng qián zǒu.", "Идите вперёд.", "в сторону, к"],
  ["南边", "nánbian", "south", "公园在南边。", "Gōngyuán zài nánbian.", "Парк находится на юге.", "юг, южная сторона"],
  ["离", "lí", "away from", "学校离银行很近。", "Xuéxiào lí yínháng hěn jìn.", "Школа находится близко к банку.", "от, на расстоянии от"],
  ["这儿", "zhèr", "here", "我在这儿。", "Wǒ zài zhèr.", "Я здесь.", "здесь"],
  ["对", "duì", "right, correct", "你说得对。", "Nǐ shuō de duì.", "Ты говоришь правильно.", "правильно, верно"],
  ["银行", "yínháng", "bank", "银行在哪儿？", "Yínháng zài nǎr?", "Где находится банк?", "банк"],
  ["附近", "fùjìn", "vicinity, nearby", "附近有邮局吗？", "Fùjìn yǒu yóujú ma?", "Рядом есть почта?", "рядом, поблизости"],
  ["前边", "qiánbian", "front", "银行在前边。", "Yínháng zài qiánbian.", "Банк находится впереди.", "спереди, впереди"],
  ["分钟", "fēnzhōng", "minute", "走五分钟就到了。", "Zǒu wǔ fēnzhōng jiù dào le.", "Пройдёте пять минут и дойдёте.", "минута"],
  ["左右", "zuǒyòu", "about", "十分钟左右。", "Shí fēnzhōng zuǒyòu.", "Около десяти минут.", "примерно, около"],
  ["东边", "dōngbian", "east side", "银行在东边。", "Yínháng zài dōngbian.", "Банк находится на восточной стороне.", "восточная сторона"],
  ["西边", "xībian", "west side", "邮局在西边。", "Yóujú zài xībian.", "Почта находится на западной стороне.", "западная сторона"],
  ["北边", "běibian", "north side", "学校在北边。", "Xuéxiào zài běibian.", "Школа находится на северной стороне.", "северная сторона"]
].map(([hanzi, pinyin, meaning, example, examplePinyin, exampleRussian, russian]) => ({
  hanzi,
  pinyin,
  meaning,
  example,
  examplePinyin,
  exampleRussian,
  russian
}));

CHINESE_WORDS.push(...EXTRA_CHINESE_WORDS);

const FINAL_CHINESE_WORDS = CHINESE_WORDS.map((item) => ({
  unit: "UNIT-1",
  ...item,
  russianExplanation: item.russianExplanation || makeChineseExplanation(item)
}));

window.CHINESE_WORDS = FINAL_CHINESE_WORDS;